print("Taller de AIPython P1 E2")
print("el","taller","es")
print("hola alumnos                     ","es viernes",sep='-')
print("probando argumentos","soy el segundo argumento", end='*')
print("soy otra linea")

print("soy seis")
print("Las maquinas me sorprenden con mucha frecuencia")
print("")
print("23",23) 
print("Una computadora puede ser llamada ''intelig|ente'' si logra engañar a una persona haciéndole creer que es un humano.")
print("Franco ","rosas","25")
# print("Franco ","rosas","25",sep='-')
print("calle \t"," numero \t"," codigo postal \t")

