print("soy seis")
print("Las maquinas me sorprenden con mucha frecuencia")
print("")
print("23",23) 
print("Una computadora puede ser llamada ''intelig|ente'' si logra engañar a una persona haciéndole creer que es un humano.")
print("Franco ","rosas","25")
# print("Franco ","rosas","25",sep='-')
print("calle \t","numero \t"," codigo postal \t")
print("calle")
print("numero")
print("codigo postal")
print("--------------")